events { worker_connections 1024; }

http {
    # Настройка кеша:
    # max_size=5g - лимит 5 гигабайт (измените под свои нужды)
    # inactive=7d - удалять файл, если его никто не запрашивал 7 дней
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=img_cache:10m max_size=5g inactive=7d use_temp_path=off;

    server {
        listen 80;

        # Проверка здоровья
        location /health {
            return 200 'OK';
        }

        location / {
            # Docker DNS
            resolver 127.0.0.11 valid=10s;
            set $imgproxy_backend http://img-imgproxy:8080;

            proxy_cache img_cache;
            proxy_pass $imgproxy_backend;

            # Кешируем успешные ответы на 30 дней
            proxy_cache_valid 200 30d;

            # Если Imgproxy упал или тормозит, отдаем старый кеш
            proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

            # Добавляем заголовок, чтобы видеть, попали мы в кеш или нет (HIT/MISS)
            add_header X-Cache-Status $upstream_cache_status;

            # Ключ кеширования (зависит от URL и хоста)
            proxy_cache_key "$host$request_uri";

            # Игнорируем заголовки управления кешем от S3, чтобы Nginx сам решал сколько хранить
            proxy_ignore_headers Cache-Control Expires Set-Cookie;
        }
    }
}
