name: CI pipeline 

on:
    push:
        branches:
            - stages
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        name: Setup, builds, tests
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install deps
              uses: npm install

            - name: Testing app
              uses: npm run test

            - name: Build app
              uses: npm run build